// Elenco real de jogadores por clube, sourced do dataset público FC26 (EA Sports FC 26)
// via Kaggle/GitHub (community dataset, licença aberta) — não é possível acessar o
// sofifa.com direto deste ambiente (bloqueado pelo proxy de rede), então a base real
// de ratings vem desse dataset em vez de scraping ao vivo. Nomes já vêm abreviados
// (formato "J. Bellingham"), igual o padrão que aparece no próprio jogo de futebol.
//
// Primeira liga populada: França (Ligue 1 + Ligue 2), a pedido do treinador. Só existe
// edição FC26 por enquanto — a FC27 ainda não tem dataset público (jogo lançado recente
// demais). Quando o dataset da FC27 aparecer, basta adicionar a chave fc27 aqui.
const jogadoresPorClubePorEdicao = {
    fc26: {
        "Ligue 1 (OVR 75)": {
            "Paris Saint-Germain": [
                { nome: "O. Dembélé", idade: 28, posicao: "ST", ovr: 90 },
                { nome: "A. Hakimi", idade: 26, posicao: "RB", ovr: 89 },
                { nome: "Vitinha", idade: 25, posicao: "CM", ovr: 89 },
                { nome: "K. Kvaratskhelia", idade: 24, posicao: "LW", ovr: 87 },
                { nome: "Marquinhos", idade: 31, posicao: "RCB", ovr: 87 },
                { nome: "Nuno Mendes", idade: 23, posicao: "LB", ovr: 86 },
                { nome: "W. Pacho", idade: 23, posicao: "LCB", ovr: 86 },
                { nome: "João Neves", idade: 20, posicao: "RCM", ovr: 85 },
                { nome: "Fabián Ruiz", idade: 29, posicao: "LCM", ovr: 85 },
                { nome: "D. Doué", idade: 20, posicao: "RW", ovr: 85 },
                { nome: "B. Barcola", idade: 22, posicao: "LW", ovr: 84 },
                { nome: "L. Chevalier", idade: 23, posicao: "GK", ovr: 83 },
                { nome: "L. Hernández", idade: 29, posicao: "CB", ovr: 81 },
                { nome: "W. Zaïre-Emery", idade: 19, posicao: "CM", ovr: 80 },
                { nome: "Gonçalo Ramos", idade: 24, posicao: "ST", ovr: 80 },
                { nome: "Lee Kang In", idade: 24, posicao: "RW", ovr: 79 },
                { nome: "I. Zabarnyi", idade: 22, posicao: "CB", ovr: 79 },
                { nome: "Lucas Beraldo", idade: 21, posicao: "CB", ovr: 78 },
                { nome: "M. Safonov", idade: 26, posicao: "GK", ovr: 78 },
                { nome: "S. Mayulu", idade: 19, posicao: "CM", ovr: 75 },
                { nome: "I. Mbaye", idade: 17, posicao: "RW", ovr: 68 },
                { nome: "N. Kamara", idade: 18, posicao: "CB", ovr: 62 },
                { nome: "Renato Marin", idade: 18, posicao: "GK", ovr: 62 }
            ],
            "Lyon": [
                { nome: "C. Tolisso", idade: 30, posicao: "CAM", ovr: 81 },
                { nome: "N. Tagliafico", idade: 32, posicao: "LB", ovr: 78 },
                { nome: "M. Fofana", idade: 20, posicao: "LM", ovr: 78 },
                { nome: "D. Greif", idade: 28, posicao: "GK", ovr: 78 },
                { nome: "A. Maitland-Niles", idade: 27, posicao: "RB", ovr: 77 },
                { nome: "Clinton Mata", idade: 32, posicao: "RCB", ovr: 77 },
                { nome: "O. Mangala", idade: 27, posicao: "CDM", ovr: 77 },
                { nome: "P. Šulc", idade: 24, posicao: "CAM", ovr: 77 },
                { nome: "M. Niakhaté", idade: 29, posicao: "LCB", ovr: 77 },
                { nome: "T. Tessmann", idade: 23, posicao: "RDM", ovr: 75 },
                { nome: "E. Nuamah", idade: 21, posicao: "RM", ovr: 75 },
                { nome: "T. Morton", idade: 22, posicao: "LDM", ovr: 74 },
                { nome: "Abner Vinícius", idade: 25, posicao: "LB", ovr: 74 },
                { nome: "R. Ghezzal", idade: 33, posicao: "RM", ovr: 74 },
                { nome: "M. Satriano", idade: 24, posicao: "ST", ovr: 74 },
                { nome: "R. Descamps", idade: 29, posicao: "GK", ovr: 74 },
                { nome: "A. Karabec", idade: 21, posicao: "RM", ovr: 71 },
                { nome: "Afonso Moreira", idade: 20, posicao: "LM", ovr: 67 },
                { nome: "R. Kluivert", idade: 24, posicao: "CB", ovr: 67 },
                { nome: "K. Merah", idade: 18, posicao: "CAM", ovr: 66 },
                { nome: "A. Laâziri", idade: 21, posicao: "LB", ovr: 65 },
                { nome: "A. Gomes Rodríguez", idade: 17, posicao: "ST", ovr: 64 },
                { nome: "E. Molebe", idade: 17, posicao: "ST", ovr: 64 },
                { nome: "L. Diarra", idade: 22, posicao: "GK", ovr: 64 },
                { nome: "M. De Carvalho", idade: 20, posicao: "CDM", ovr: 63 },
                { nome: "T. Barišić", idade: 20, posicao: "RB", ovr: 63 }
            ],
            "Marseille": [
                { nome: "B. Pavard", idade: 29, posicao: "RCB", ovr: 84 },
                { nome: "P. Højbjerg", idade: 29, posicao: "LDM", ovr: 82 },
                { nome: "M. Greenwood", idade: 23, posicao: "RM", ovr: 82 },
                { nome: "G. Rulli", idade: 33, posicao: "GK", ovr: 82 },
                { nome: "P. Aubameyang", idade: 36, posicao: "ST", ovr: 81 },
                { nome: "N. Aguerd", idade: 29, posicao: "LCB", ovr: 81 },
                { nome: "L. Balerdi", idade: 26, posicao: "CB", ovr: 81 },
                { nome: "Igor Paixão", idade: 25, posicao: "LM", ovr: 80 },
                { nome: "A. Gouiri", idade: 25, posicao: "ST", ovr: 79 },
                { nome: "F. Medina", idade: 26, posicao: "LB", ovr: 79 },
                { nome: "M. O'Riley", idade: 24, posicao: "CAM", ovr: 78 },
                { nome: "G. Kondogbia", idade: 32, posicao: "CB", ovr: 78 },
                { nome: "T. Weah", idade: 25, posicao: "RM", ovr: 77 },
                { nome: "Emerson", idade: 30, posicao: "LB", ovr: 77 },
                { nome: "H. Traoré", idade: 25, posicao: "LM", ovr: 77 },
                { nome: "A. Vermeeren", idade: 20, posicao: "CM", ovr: 77 },
                { nome: "A. Gomes", idade: 24, posicao: "RDM", ovr: 76 },
                { nome: "A. Murillo", idade: 29, posicao: "RB", ovr: 76 },
                { nome: "N. Maupay", idade: 28, posicao: "ST", ovr: 75 },
                { nome: "U. Garcia", idade: 29, posicao: "LB", ovr: 75 },
                { nome: "C. Egan-Riley", idade: 22, posicao: "CB", ovr: 75 },
                { nome: "Pol Lirola", idade: 27, posicao: "RB", ovr: 73 },
                { nome: "Rubén Blanco", idade: 29, posicao: "GK", ovr: 73 },
                { nome: "J. de Lange", idade: 27, posicao: "GK", ovr: 73 },
                { nome: "B. Nadir", idade: 21, posicao: "CAM", ovr: 71 },
                { nome: "R. Vaz", idade: 18, posicao: "ST", ovr: 64 },
                { nome: "D. Bakola", idade: 17, posicao: "CAM", ovr: 63 },
                { nome: "F. Mughe", idade: 21, posicao: "RM", ovr: 63 },
                { nome: "K. Abdallah", idade: 19, posicao: "RM", ovr: 62 },
                { nome: "Y. Sellami", idade: 18, posicao: "CM", ovr: 61 },
                { nome: "J. Van Neck", idade: 21, posicao: "GK", ovr: 61 },
                { nome: "T. Vermot", idade: 28, posicao: "GK", ovr: 59 }
            ],
            "Nice": [
                { nome: "J. Clauss", idade: 32, posicao: "RM", ovr: 80 },
                { nome: "M. Bard", idade: 24, posicao: "LM", ovr: 78 },
                { nome: "Dante", idade: 41, posicao: "LCB", ovr: 78 },
                { nome: "Y. Diouf", idade: 25, posicao: "GK", ovr: 78 },
                { nome: "H. Boudaoui", idade: 25, posicao: "RCM", ovr: 77 },
                { nome: "C. Vanhoutte", idade: 26, posicao: "LCM", ovr: 77 },
                { nome: "Y. Ndayishimiye", idade: 26, posicao: "CB", ovr: 77 },
                { nome: "M. Sanson", idade: 30, posicao: "CM", ovr: 76 },
                { nome: "A. Abdi", idade: 31, posicao: "LB", ovr: 76 },
                { nome: "S. Diop", idade: 25, posicao: "LW", ovr: 76 },
                { nome: "J. Boga", idade: 28, posicao: "LW", ovr: 76 },
                { nome: "M. Bombito", idade: 25, posicao: "CB", ovr: 76 },
                { nome: "M. Cho", idade: 21, posicao: "RW", ovr: 76 },
                { nome: "T. Moffi", idade: 26, posicao: "ST", ovr: 75 },
                { nome: "T. Ndombele", idade: 28, posicao: "CM", ovr: 74 },
                { nome: "M. Abdelmonem", idade: 26, posicao: "CB", ovr: 74 },
                { nome: "M. Dupé", idade: 32, posicao: "GK", ovr: 74 },
                { nome: "Tiago Gouveia", idade: 24, posicao: "RM", ovr: 73 },
                { nome: "S. Abdul Samed", idade: 25, posicao: "CDM", ovr: 73 },
                { nome: "T. Louchet", idade: 22, posicao: "RM", ovr: 72 },
                { nome: "Kevin Carlos", idade: 24, posicao: "ST", ovr: 72 },
                { nome: "A. Bah", idade: 19, posicao: "CB", ovr: 72 },
                { nome: "I. Jansson", idade: 23, posicao: "LW", ovr: 71 },
                { nome: "A. Mendy", idade: 21, posicao: "CB", ovr: 70 },
                { nome: "K. Oppong", idade: 21, posicao: "RCB", ovr: 68 },
                { nome: "G. Bernardeau", idade: 19, posicao: "CAM", ovr: 66 },
                { nome: "B. Żelazowski", idade: 20, posicao: "GK", ovr: 62 },
                { nome: "B. Nguene", idade: 18, posicao: "ST", ovr: 60 }
            ],
            "Monaco": [
                { nome: "D. Zakaria", idade: 28, posicao: "LCM", ovr: 82 },
                { nome: "L. Hrádecký", idade: 35, posicao: "GK", ovr: 81 },
                { nome: "M. Akliouche", idade: 23, posicao: "RM", ovr: 80 },
                { nome: "A. Golovin", idade: 29, posicao: "LM", ovr: 79 },
                { nome: "P. Pogba", idade: 32, posicao: "CM", ovr: 79 },
                { nome: "E. Dier", idade: 31, posicao: "RCB", ovr: 79 },
                { nome: "T. Kehrer", idade: 28, posicao: "CB", ovr: 79 },
                { nome: "T. Minamino", idade: 30, posicao: "LM", ovr: 78 },
                { nome: "M. Biereth", idade: 22, posicao: "LS", ovr: 78 },
                { nome: "L. Camara", idade: 21, posicao: "RCM", ovr: 77 },
                { nome: "Vanderson", idade: 24, posicao: "RB", ovr: 77 },
                { nome: "Caio Henrique", idade: 27, posicao: "LB", ovr: 77 },
                { nome: "F. Balogun", idade: 23, posicao: "RS", ovr: 77 },
                { nome: "P. Köhn", idade: 27, posicao: "GK", ovr: 77 },
                { nome: "J. Teze", idade: 25, posicao: "RB", ovr: 76 },
                { nome: "M. Salisu", idade: 26, posicao: "CB", ovr: 76 },
                { nome: "Ansu Fati", idade: 22, posicao: "LM", ovr: 75 },
                { nome: "C. Mawissa", idade: 20, posicao: "LCB", ovr: 75 },
                { nome: "K. Diatta", idade: 26, posicao: "RM", ovr: 74 },
                { nome: "K. Ouattara", idade: 20, posicao: "LB", ovr: 72 },
                { nome: "G. Ilenikhena", idade: 18, posicao: "ST", ovr: 72 },
                { nome: "S. Idumbo", idade: 20, posicao: "CAM", ovr: 67 },
                { nome: "P. Brunner", idade: 19, posicao: "ST", ovr: 66 },
                { nome: "A. Bamba", idade: 18, posicao: "CDM", ovr: 65 },
                { nome: "Y. Lienard", idade: 22, posicao: "GK", ovr: 65 },
                { nome: "M. Coulibaly", idade: 21, posicao: "CM", ovr: 64 },
                { nome: "L. Michal", idade: 20, posicao: "LM", ovr: 64 },
                { nome: "J. Stawiecki", idade: 18, posicao: "GK", ovr: 60 }
            ],
            "Lille": [
                { nome: "B. André", idade: 34, posicao: "RDM", ovr: 80 },
                { nome: "Alexsandro", idade: 25, posicao: "LCB", ovr: 80 },
                { nome: "O. Giroud", idade: 38, posicao: "ST", ovr: 79 },
                { nome: "H. Haraldsson", idade: 22, posicao: "CAM", ovr: 78 },
                { nome: "N. Bentaleb", idade: 30, posicao: "CDM", ovr: 77 },
                { nome: "Tiago Santos", idade: 22, posicao: "RB", ovr: 77 },
                { nome: "B. Özer", idade: 25, posicao: "GK", ovr: 77 },
                { nome: "T. Meunier", idade: 33, posicao: "RB", ovr: 76 },
                { nome: "O. Sahraoui", idade: 24, posicao: "LM", ovr: 76 },
                { nome: "André Gomes", idade: 31, posicao: "CDM", ovr: 75 },
                { nome: "A. Bouaddi", idade: 17, posicao: "LDM", ovr: 75 },
                { nome: "A. Mandi", idade: 33, posicao: "CB", ovr: 75 },
                { nome: "Félix Correia", idade: 24, posicao: "LM", ovr: 75 },
                { nome: "C. Mbemba", idade: 30, posicao: "CB", ovr: 75 },
                { nome: "M. Fernandez-Pardo", idade: 20, posicao: "RM", ovr: 75 },
                { nome: "R. Perraud", idade: 27, posicao: "LB", ovr: 74 },
                { nome: "N. Mukau", idade: 20, posicao: "CDM", ovr: 74 },
                { nome: "H. Igamane", idade: 22, posicao: "ST", ovr: 73 },
                { nome: "A. Bodart", idade: 27, posicao: "GK", ovr: 73 },
                { nome: "C. Verdonk", idade: 28, posicao: "LB", ovr: 71 },
                { nome: "U. Raghouber", idade: 21, posicao: "CDM", ovr: 69 },
                { nome: "E. Mbappé", idade: 18, posicao: "CM", ovr: 69 },
                { nome: "M. Broholm", idade: 20, posicao: "RM", ovr: 69 },
                { nome: "N. Ngoy", idade: 22, posicao: "RCB", ovr: 69 },
                { nome: "M. Caillard", idade: 31, posicao: "GK", ovr: 67 },
                { nome: "O. Touré", idade: 20, posicao: "CB", ovr: 65 },
                { nome: "T. Dago", idade: 20, posicao: "ST", ovr: 63 },
                { nome: "Rafael Fernandes", idade: 23, posicao: "CB", ovr: 63 },
                { nome: "M. Goffi", idade: 17, posicao: "CB", ovr: 62 }
            ],
            "Rennes": [
                { nome: "B. Samba", idade: 31, posicao: "GK", ovr: 80 },
                { nome: "V. Rongier", idade: 30, posicao: "RCM", ovr: 79 },
                { nome: "M. Camara", idade: 27, posicao: "CM", ovr: 78 },
                { nome: "S. Fofana", idade: 30, posicao: "LCM", ovr: 77 },
                { nome: "L. Blas", idade: 27, posicao: "RM", ovr: 77 },
                { nome: "B. Embolo", idade: 28, posicao: "ST", ovr: 77 },
                { nome: "Q. Merlin", idade: 23, posicao: "LB", ovr: 76 },
                { nome: "H. Hateboer", idade: 31, posicao: "CB", ovr: 76 },
                { nome: "L. Brassier", idade: 25, posicao: "CB", ovr: 76 },
                { nome: "A. Rouault", idade: 24, posicao: "LCB", ovr: 76 },
                { nome: "P. Frankowski", idade: 30, posicao: "RB", ovr: 75 },
                { nome: "M. Al Tamari", idade: 28, posicao: "RS", ovr: 75 },
                { nome: "E. Lepaul", idade: 25, posicao: "LS", ovr: 75 },
                { nome: "J. Jacquet", idade: 19, posicao: "CB", ovr: 75 },
                { nome: "G. Kamara", idade: 29, posicao: "CDM", ovr: 74 },
                { nome: "A. Seidu", idade: 25, posicao: "CB", ovr: 74 },
                { nome: "D. Cissé", idade: 21, posicao: "CDM", ovr: 73 },
                { nome: "G. Gallon", idade: 32, posicao: "GK", ovr: 73 },
                { nome: "M. Meïté", idade: 17, posicao: "ST", ovr: 70 },
                { nome: "A. Ait Boudlal", idade: 19, posicao: "RCB", ovr: 68 },
                { nome: "M. Nagida", idade: 20, posicao: "LB", ovr: 66 }
            ],
            "Lens": [
                { nome: "A. Thomasson", idade: 31, posicao: "LCM", ovr: 77 },
                { nome: "J. Gradit", idade: 32, posicao: "RCB", ovr: 77 },
                { nome: "D. Machado", idade: 31, posicao: "LM", ovr: 76 },
                { nome: "F. Thauvin", idade: 32, posicao: "RW", ovr: 76 },
                { nome: "R. Aguilar", idade: 32, posicao: "RM", ovr: 76 },
                { nome: "F. Sotoca", idade: 34, posicao: "ST", ovr: 75 },
                { nome: "S. Abdulhamid", idade: 25, posicao: "RB", ovr: 75 },
                { nome: "M. Udol", idade: 29, posicao: "LCB", ovr: 74 },
                { nome: "A. Sima", idade: 24, posicao: "LW", ovr: 74 },
                { nome: "W. Saïd", idade: 30, posicao: "ST", ovr: 74 },
                { nome: "M. Guilavogui", idade: 27, posicao: "ST", ovr: 73 },
                { nome: "M. Sarr", idade: 26, posicao: "CB", ovr: 73 },
                { nome: "M. Sangaré", idade: 23, posicao: "RCM", ovr: 72 },
                { nome: "J. Chávez", idade: 23, posicao: "LB", ovr: 72 },
                { nome: "O. Edouard", idade: 27, posicao: "ST", ovr: 72 },
                { nome: "R. Risser", idade: 20, posicao: "GK", ovr: 72 },
                { nome: "H. Ojediran", idade: 21, posicao: "CDM", ovr: 70 },
                { nome: "S. Baidoo", idade: 21, posicao: "CB", ovr: 70 },
                { nome: "R. Gurtner", idade: 38, posicao: "GK", ovr: 69 },
                { nome: "A. Bermont", idade: 20, posicao: "LM", ovr: 68 },
                { nome: "I. Ganiou", idade: 20, posicao: "RB", ovr: 66 },
                { nome: "F. Sylla", idade: 19, posicao: "CM", ovr: 65 },
                { nome: "R. Fofana", idade: 19, posicao: "ST", ovr: 65 },
                { nome: "A. Bulatović", idade: 18, posicao: "CM", ovr: 64 },
                { nome: "K. Antonio", idade: 17, posicao: "CB", ovr: 64 },
                { nome: "N. Čelik", idade: 18, posicao: "CB", ovr: 64 },
                { nome: "A. Diallo", idade: 19, posicao: "CM", ovr: 62 },
                { nome: "I. Jourdren", idade: 16, posicao: "GK", ovr: 60 }
            ],
            "Paris FC": [
                { nome: "K. Trapp", idade: 34, posicao: "GK", ovr: 81 },
                { nome: "H. Traoré", idade: 33, posicao: "RB", ovr: 79 },
                { nome: "P. Lees-Melou", idade: 32, posicao: "CDM", ovr: 78 },
                { nome: "M. Simon", idade: 29, posicao: "LM", ovr: 77 },
                { nome: "M. Lopez", idade: 27, posicao: "RCM", ovr: 76 },
                { nome: "J. Ikoné", idade: 27, posicao: "RM", ovr: 76 },
                { nome: "I. Kebbal", idade: 26, posicao: "RM", ovr: 76 },
                { nome: "Otávio", idade: 23, posicao: "LCB", ovr: 75 },
                { nome: "J. Krasso", idade: 27, posicao: "ST", ovr: 74 },
                { nome: "M. Cafaro", idade: 28, posicao: "LM", ovr: 73 },
                { nome: "O. Nkambadio", idade: 22, posicao: "GK", ovr: 73 },
                { nome: "T. De Smet", idade: 27, posicao: "LB", ovr: 72 },
                { nome: "W. Geubbels", idade: 23, posicao: "ST", ovr: 72 },
                { nome: "M. Mbow", idade: 25, posicao: "RCB", ovr: 72 },
                { nome: "A. Camara", idade: 28, posicao: "CM", ovr: 71 },
                { nome: "V. Marchetti", idade: 27, posicao: "LCM", ovr: 70 },
                { nome: "T. Kolodziejczak", idade: 33, posicao: "CB", ovr: 69 },
                { nome: "A. Gory", idade: 28, posicao: "ST", ovr: 69 },
                { nome: "T. Ollila", idade: 25, posicao: "LB", ovr: 68 },
                { nome: "L. Doucet", idade: 22, posicao: "CDM", ovr: 68 },
                { nome: "N. Dicko", idade: 33, posicao: "ST", ovr: 67 },
                { nome: "J. Lopez", idade: 33, posicao: "CAM", ovr: 67 },
                { nome: "N. Sangui", idade: 19, posicao: "LB", ovr: 67 },
                { nome: "S. Chergui", idade: 26, posicao: "CB", ovr: 67 },
                { nome: "P. Hamel", idade: 31, posicao: "ST", ovr: 67 },
                { nome: "R. Riou", idade: 37, posicao: "GK", ovr: 67 },
                { nome: "S. Alakouch", idade: 26, posicao: "RB", ovr: 65 },
                { nome: "L. Gueye", idade: 27, posicao: "RM", ovr: 64 },
                { nome: "A. Pembélé", idade: 24, posicao: "RM", ovr: 62 }
            ],
            "Strasbourg": [
                { nome: "E. Emegha", idade: 22, posicao: "ST", ovr: 78 },
                { nome: "B. Chilwell", idade: 28, posicao: "LM", ovr: 77 },
                { nome: "Diego Moreira", idade: 20, posicao: "RM", ovr: 77 },
                { nome: "G. Doué", idade: 22, posicao: "RCB", ovr: 77 },
                { nome: "F. Lemaréchal", idade: 21, posicao: "RAM", ovr: 76 },
                { nome: "S. Nanasi", idade: 23, posicao: "LAM", ovr: 76 },
                { nome: "I. Doukouré", idade: 21, posicao: "LCB", ovr: 76 },
                { nome: "M. Sarr", idade: 19, posicao: "CB", ovr: 76 },
                { nome: "V. Barco", idade: 20, posicao: "LCM", ovr: 75 },
                { nome: "J. Panichelli", idade: 22, posicao: "ST", ovr: 74 },
                { nome: "K. Páez", idade: 18, posicao: "CAM", ovr: 73 },
                { nome: "J. Enciso", idade: 21, posicao: "CAM", ovr: 73 },
                { nome: "A. Omobamidele", idade: 23, posicao: "CB", ovr: 73 },
                { nome: "M. Penders", idade: 19, posicao: "GK", ovr: 73 },
                { nome: "M. Amougou", idade: 19, posicao: "RCM", ovr: 72 },
                { nome: "A. Sylla", idade: 22, posicao: "CB", ovr: 72 },
                { nome: "S. Coulibaly", idade: 21, posicao: "CB", ovr: 72 },
                { nome: "S. Sow", idade: 22, posicao: "CB", ovr: 71 },
                { nome: "M. Oyedele", idade: 20, posicao: "CM", ovr: 70 },
                { nome: "E. Sobol", idade: 30, posicao: "LB", ovr: 69 },
                { nome: "R. Nzingoula", idade: 19, posicao: "CDM", ovr: 69 },
                { nome: "L. Høgsberg", idade: 19, posicao: "CB", ovr: 69 },
                { nome: "S. Amo-Ameyaw", idade: 18, posicao: "RM", ovr: 69 },
                { nome: "K. Johnsson", idade: 35, posicao: "GK", ovr: 69 },
                { nome: "A. Ouattara", idade: 19, posicao: "RM", ovr: 68 },
                { nome: "Rafael Luís", idade: 20, posicao: "CDM", ovr: 67 },
                { nome: "S. El Mourabet", idade: 19, posicao: "CM", ovr: 66 },
                { nome: "M. Godo", idade: 22, posicao: "RM", ovr: 65 },
                { nome: "S. Bajic", idade: 23, posicao: "GK", ovr: 65 }
            ],
            "Brest": [
                { nome: "L. Ajorque", idade: 31, posicao: "ST", ovr: 77 },
                { nome: "B. Chardonnet", idade: 30, posicao: "RCB", ovr: 77 },
                { nome: "R. Majecki", idade: 25, posicao: "GK", ovr: 77 },
                { nome: "K. Lala", idade: 33, posicao: "RB", ovr: 76 },
                { nome: "R. Del Castillo", idade: 29, posicao: "RW", ovr: 76 },
                { nome: "H. Magnetti", idade: 27, posicao: "LCM", ovr: 76 },
                { nome: "B. Locko", idade: 23, posicao: "LB", ovr: 75 },
                { nome: "J. Chotard", idade: 23, posicao: "CM", ovr: 74 },
                { nome: "K. Doumbia", idade: 22, posicao: "RCM", ovr: 74 },
                { nome: "L. Tousart", idade: 28, posicao: "CDM", ovr: 74 },
                { nome: "J. Le Cardinal", idade: 27, posicao: "LCB", ovr: 74 },
                { nome: "Mama Baldé", idade: 29, posicao: "LW", ovr: 73 },
                { nome: "J. Dina Ebimbe", idade: 24, posicao: "RM", ovr: 72 },
                { nome: "R. Labeau Lascary", idade: 22, posicao: "ST", ovr: 72 },
                { nome: "P. Mboup", idade: 21, posicao: "LM", ovr: 69 },
                { nome: "J. Diaz", idade: 21, posicao: "CB", ovr: 69 },
                { nome: "L. Zogbé", idade: 20, posicao: "RB", ovr: 68 },
                { nome: "D. Guindo", idade: 22, posicao: "LB", ovr: 67 },
                { nome: "G. Coudert", idade: 26, posicao: "GK", ovr: 66 },
                { nome: "J. Bourgault", idade: 19, posicao: "LB", ovr: 65 },
                { nome: "H. Makalou", idade: 18, posicao: "CDM", ovr: 63 },
                { nome: "R. Le Guen", idade: 18, posicao: "CB", ovr: 62 },
                { nome: "N. Jauny", idade: 20, posicao: "GK", ovr: 58 },
                { nome: "S. Diop", idade: 20, posicao: "ST", ovr: 57 }
            ],
            "Angers": [
                { nome: "H. Abdelli", idade: 25, posicao: "CAM", ovr: 76 },
                { nome: "H. Belkebla", idade: 31, posicao: "LDM", ovr: 74 },
                { nome: "J. Lefort", idade: 31, posicao: "LCB", ovr: 73 },
                { nome: "H. Koffi", idade: 28, posicao: "GK", ovr: 73 },
                { nome: "F. Hanin", idade: 35, posicao: "LB", ovr: 72 },
                { nome: "J. Allevinah", idade: 30, posicao: "RM", ovr: 72 },
                { nome: "C. Arcus", idade: 29, posicao: "RB", ovr: 71 },
                { nome: "P. Capelle", idade: 38, posicao: "CDM", ovr: 70 },
                { nome: "Y. Belkhdim", idade: 23, posicao: "RDM", ovr: 70 },
                { nome: "L. Mouton", idade: 23, posicao: "CM", ovr: 70 },
                { nome: "A. Bamba", idade: 35, posicao: "CB", ovr: 70 },
                { nome: "L. Raolisoa", idade: 25, posicao: "RB", ovr: 70 },
                { nome: "E. Biumla", idade: 20, posicao: "CB", ovr: 70 },
                { nome: "O. Camara", idade: 22, posicao: "RCB", ovr: 69 },
                { nome: "J. Ekomié", idade: 21, posicao: "LB", ovr: 68 },
                { nome: "S. Chérif", idade: 18, posicao: "LM", ovr: 67 },
                { nome: "M. Courcoul", idade: 18, posicao: "CDM", ovr: 65 },
                { nome: "M. Zinga", idade: 23, posicao: "GK", ovr: 65 },
                { nome: "J. Kalumba", idade: 20, posicao: "LM", ovr: 63 },
                { nome: "P. Peter", idade: 17, posicao: "ST", ovr: 63 },
                { nome: "L. Machine", idade: 19, posicao: "ST", ovr: 61 },
                { nome: "N. Nadje", idade: 21, posicao: "ST", ovr: 59 },
                { nome: "I. Garin", idade: 19, posicao: "CDM", ovr: 58 },
                { nome: "L. Ngangué", idade: 20, posicao: "LB", ovr: 58 },
                { nome: "M. Louër", idade: 18, posicao: "RB", ovr: 58 },
                { nome: "J. El Baraka", idade: 18, posicao: "CDM", ovr: 57 },
                { nome: "D. Sinaté", idade: 19, posicao: "LB", ovr: 57 },
                { nome: "A. Moussaoui", idade: 18, posicao: "CAM", ovr: 57 },
                { nome: "O. Pona", idade: 19, posicao: "GK", ovr: 57 }
            ],
            "Toulouse": [
                { nome: "G. Restes", idade: 20, posicao: "GK", ovr: 78 },
                { nome: "R. Nicolaisen", idade: 28, posicao: "LCB", ovr: 76 },
                { nome: "A. Dønnum", idade: 27, posicao: "RM", ovr: 75 },
                { nome: "Y. Gboho", idade: 24, posicao: "LW", ovr: 75 },
                { nome: "C. Cásseres Jr", idade: 25, posicao: "LCM", ovr: 74 },
                { nome: "D. Sidibé", idade: 32, posicao: "RCB", ovr: 74 },
                { nome: "M. McKenzie", idade: 26, posicao: "CB", ovr: 74 },
                { nome: "C. Cresswell", idade: 22, posicao: "CB", ovr: 74 },
                { nome: "N. Schmidt", idade: 27, posicao: "CM", ovr: 72 },
                { nome: "W. Kamanzi", idade: 24, posicao: "RB", ovr: 72 },
                { nome: "F. Magri", idade: 25, posicao: "ST", ovr: 72 },
                { nome: "K. Haug", idade: 27, posicao: "GK", ovr: 70 },
                { nome: "S. Hidalgo", idade: 20, posicao: "RW", ovr: 69 },
                { nome: "A. Francis", idade: 24, posicao: "CM", ovr: 68 },
                { nome: "M. Sauer", idade: 21, posicao: "RCM", ovr: 68 },
                { nome: "N. Edjouma", idade: 19, posicao: "RM", ovr: 66 },
                { nome: "Álex Domínguez", idade: 26, posicao: "GK", ovr: 66 },
                { nome: "Emersonn", idade: 20, posicao: "RW", ovr: 65 },
                { nome: "J. Vignolo", idade: 18, posicao: "ST", ovr: 65 },
                { nome: "R. Messali", idade: 22, posicao: "RB", ovr: 64 },
                { nome: "D. Methalie", idade: 19, posicao: "LM", ovr: 64 },
                { nome: "N. Lahmadi", idade: 20, posicao: "CM", ovr: 62 },
                { nome: "D. Zema", idade: 18, posicao: "RW", ovr: 62 },
                { nome: "N. Wasbauer", idade: 20, posicao: "CB", ovr: 62 },
                { nome: "A. Vossah", idade: 17, posicao: "CDM", ovr: 61 },
                { nome: "I. Azizi", idade: 17, posicao: "LW", ovr: 61 },
                { nome: "F. Efuele Ngoyala", idade: 20, posicao: "CB", ovr: 61 },
                { nome: "S. Koumbassa", idade: 18, posicao: "CB", ovr: 61 },
                { nome: "E. Faty", idade: 18, posicao: "ST", ovr: 60 },
                { nome: "G. Bakhouche", idade: 20, posicao: "CB", ovr: 59 },
                { nome: "N. Saïd Mchindra", idade: 20, posicao: "GK", ovr: 58 }
            ],
            "Nantes": [
                { nome: "M. Abline", idade: 22, posicao: "ST", ovr: 76 },
                { nome: "A. Lopes", idade: 34, posicao: "GK", ovr: 76 },
                { nome: "F. Coquelin", idade: 34, posicao: "CDM", ovr: 75 },
                { nome: "J. Lepenant", idade: 22, posicao: "LCM", ovr: 74 },
                { nome: "Hong Hyeon Seok", idade: 26, posicao: "CAM", ovr: 73 },
                { nome: "K. Amian", idade: 27, posicao: "RB", ovr: 73 },
                { nome: "Y. El Arabi", idade: 38, posicao: "ST", ovr: 73 },
                { nome: "M. Mohamed", idade: 27, posicao: "ST", ovr: 73 },
                { nome: "N. Cozza", idade: 26, posicao: "LB", ovr: 73 },
                { nome: "J. Mwanga", idade: 22, posicao: "CDM", ovr: 72 },
                { nome: "P. Carlgren", idade: 33, posicao: "GK", ovr: 71 },
                { nome: "F. Centonze", idade: 29, posicao: "RB", ovr: 70 },
                { nome: "L. Leroux", idade: 19, posicao: "RCM", ovr: 70 },
                { nome: "C. Awaziem", idade: 28, posicao: "RCB", ovr: 70 },
                { nome: "M. Lahdo", idade: 22, posicao: "RW", ovr: 68 },
                { nome: "Kwon Hyeok Kyu", idade: 24, posicao: "CDM", ovr: 67 },
                { nome: "Y. Benhattab", idade: 22, posicao: "RW", ovr: 67 },
                { nome: "B. Guirassy", idade: 18, posicao: "LW", ovr: 67 },
                { nome: "T. Tati", idade: 17, posicao: "LCB", ovr: 67 },
                { nome: "U. Radaković", idade: 31, posicao: "CB", ovr: 67 },
                { nome: "D. Tabibou", idade: 20, posicao: "CM", ovr: 64 },
                { nome: "A. Mahamoud", idade: 22, posicao: "LW", ovr: 64 },
                { nome: "A. Camara", idade: 20, posicao: "ST", ovr: 63 },
                { nome: "S. Doucouré", idade: 20, posicao: "CB", ovr: 63 },
                { nome: "B. Deuff", idade: 19, posicao: "CDM", ovr: 62 },
                { nome: "A. Mirbach", idade: 20, posicao: "GK", ovr: 58 }
            ],
            "Metz": [
                { nome: "G. Hein", idade: 28, posicao: "CAM", ovr: 76 },
                { nome: "B. Stambouli", idade: 34, posicao: "RDM", ovr: 73 },
                { nome: "J. Deminguet", idade: 27, posicao: "CM", ovr: 72 },
                { nome: "F. Ballo-Touré", idade: 28, posicao: "LB", ovr: 72 },
                { nome: "C. Sabaly", idade: 26, posicao: "ST", ovr: 72 },
                { nome: "H. Diallo", idade: 30, posicao: "ST", ovr: 72 },
                { nome: "G. Tsitaishvili", idade: 24, posicao: "RM", ovr: 72 },
                { nome: "B. Traoré", idade: 23, posicao: "LDM", ovr: 71 },
                { nome: "K. Kouao", idade: 27, posicao: "RB", ovr: 71 },
                { nome: "S. Sané", idade: 21, posicao: "RCB", ovr: 70 },
                { nome: "M. Colin", idade: 33, posicao: "RB", ovr: 69 },
                { nome: "T. Yegbe", idade: 24, posicao: "CB", ovr: 69 },
                { nome: "J. Fischer", idade: 23, posicao: "GK", ovr: 69 },
                { nome: "J. Gbamin", idade: 29, posicao: "LCB", ovr: 68 },
                { nome: "J. Asoro", idade: 26, posicao: "RM", ovr: 67 },
                { nome: "U. Mboula", idade: 22, posicao: "CB", ovr: 67 },
                { nome: "Y. Lawson", idade: 20, posicao: "LB", ovr: 66 },
                { nome: "G. Abuashvili", idade: 22, posicao: "LM", ovr: 66 },
                { nome: "M. Mbaye", idade: 21, posicao: "RM", ovr: 65 },
                { nome: "M. Bokele", idade: 21, posicao: "LM", ovr: 65 },
                { nome: "A. Touré", idade: 19, posicao: "CDM", ovr: 63 },
                { nome: "I. Sané", idade: 20, posicao: "ST", ovr: 63 },
                { nome: "P. Sy", idade: 28, posicao: "GK", ovr: 63 },
                { nome: "C. Mélières", idade: 20, posicao: "RB", ovr: 61 },
                { nome: "J. Mangondo", idade: 19, posicao: "ST", ovr: 58 },
                { nome: "I. Guerti", idade: 20, posicao: "CAM", ovr: 55 }
            ],
            "Le Havre": [
                { nome: "A. Touré", idade: 31, posicao: "CDM", ovr: 75 },
                { nome: "G. Lloris", idade: 29, posicao: "LCB", ovr: 74 },
                { nome: "Y. Kechta", idade: 23, posicao: "RCM", ovr: 73 },
                { nome: "A. Sangante", idade: 23, posicao: "RCB", ovr: 73 },
                { nome: "L. Négo", idade: 34, posicao: "RB", ovr: 72 },
                { nome: "R. Khadra", idade: 23, posicao: "CAM", ovr: 72 },
                { nome: "A. Samatta", idade: 32, posicao: "ST", ovr: 72 },
                { nome: "I. Soumaré", idade: 24, posicao: "LM", ovr: 72 },
                { nome: "É. Youté Kinkoué", idade: 23, posicao: "CB", ovr: 72 },
                { nome: "T. Delaine", idade: 33, posicao: "LB", ovr: 71 },
                { nome: "Y. Namli", idade: 31, posicao: "RM", ovr: 71 },
                { nome: "R. Ndiaye", idade: 23, posicao: "LCM", ovr: 70 },
                { nome: "Y. Zouaoui", idade: 27, posicao: "LB", ovr: 70 },
                { nome: "M. Diaw", idade: 32, posicao: "GK", ovr: 70 },
                { nome: "F. Doucouré", idade: 24, posicao: "RM", ovr: 69 },
                { nome: "A. Seko", idade: 25, posicao: "CB", ovr: 69 },
                { nome: "L. Mpasi", idade: 30, posicao: "GK", ovr: 67 },
                { nome: "F. Mambimbi", idade: 24, posicao: "ST", ovr: 66 },
                { nome: "G. Kyeremeh", idade: 25, posicao: "RM", ovr: 66 },
                { nome: "S. Ebonog", idade: 20, posicao: "CM", ovr: 65 },
                { nome: "D. Pizarro", idade: 20, posicao: "ST", ovr: 65 },
                { nome: "É. Logbo", idade: 21, posicao: "ST", ovr: 65 },
                { nome: "D. Mosengo", idade: 18, posicao: "CM", ovr: 63 },
                { nome: "G. Zohouri", idade: 18, posicao: "CM", ovr: 61 },
                { nome: "P. Argney", idade: 19, posicao: "GK", ovr: 60 }
            ],
            "Lorient": [
                { nome: "Y. Mvogo", idade: 31, posicao: "GK", ovr: 76 },
                { nome: "L. Abergel", idade: 32, posicao: "LCM", ovr: 75 },
                { nome: "B. Meïté", idade: 23, posicao: "RCB", ovr: 73 },
                { nome: "M. Talbi", idade: 27, posicao: "LCB", ovr: 73 },
                { nome: "D. Yongwa", idade: 24, posicao: "LB", ovr: 72 },
                { nome: "A. Tosin", idade: 27, posicao: "LS", ovr: 71 },
                { nome: "A. Avom Ebong", idade: 20, posicao: "RCM", ovr: 71 },
                { nome: "B. Dieng", idade: 25, posicao: "ST", ovr: 71 },
                { nome: "J. Mvuka", idade: 22, posicao: "RM", ovr: 71 },
                { nome: "S. Soumano", idade: 24, posicao: "RS", ovr: 71 },
                { nome: "I. Touré", idade: 22, posicao: "CB", ovr: 71 },
                { nome: "Igor Silva", idade: 28, posicao: "RB", ovr: 70 },
                { nome: "N. Cadiou", idade: 26, posicao: "CDM", ovr: 70 },
                { nome: "P. Katseris", idade: 23, posicao: "RM", ovr: 70 },
                { nome: "M. Bamba", idade: 23, posicao: "ST", ovr: 70 },
                { nome: "B. Kamara", idade: 28, posicao: "GK", ovr: 70 },
                { nome: "J. Makengo", idade: 27, posicao: "CM", ovr: 69 },
                { nome: "T. Le Bris", idade: 22, posicao: "LM", ovr: 69 },
                { nome: "D. Karim", idade: 21, posicao: "CDM", ovr: 69 },
                { nome: "P. Pagis", idade: 22, posicao: "LM", ovr: 68 },
                { nome: "A. Faye", idade: 20, posicao: "CB", ovr: 68 },
                { nome: "B. Leroy", idade: 36, posicao: "GK", ovr: 68 },
                { nome: "N. Adjei", idade: 22, posicao: "CB", ovr: 67 },
                { nome: "A. Kouassi", idade: 20, posicao: "LB", ovr: 66 },
                { nome: "B. Fadiga", idade: 24, posicao: "CM", ovr: 63 },
                { nome: "T. Sanusi", idade: 18, posicao: "LW", ovr: 61 }
            ],
            "Auxerre": [
                { nome: "D. Léon", idade: 32, posicao: "GK", ovr: 76 },
                { nome: "G. Mensah", idade: 26, posicao: "LB", ovr: 74 },
                { nome: "L. Sinayoko", idade: 25, posicao: "ST", ovr: 74 },
                { nome: "K. Danois", idade: 21, posicao: "LCM", ovr: 74 },
                { nome: "C. Akpa", idade: 23, posicao: "LCB", ovr: 74 },
                { nome: "E. Owusu", idade: 27, posicao: "RCM", ovr: 73 },
                { nome: "S. Diomandé", idade: 24, posicao: "RCB", ovr: 73 },
                { nome: "D. Namaso", idade: 24, posicao: "ST", ovr: 73 },
                { nome: "I. Osman", idade: 20, posicao: "LM", ovr: 72 },
                { nome: "J. Casimir", idade: 23, posicao: "RM", ovr: 71 },
                { nome: "S. Mara", idade: 22, posicao: "ST", ovr: 70 },
                { nome: "F. Sierralta", idade: 28, posicao: "CB", ovr: 70 },
                { nome: "A. Dioussé", idade: 27, posicao: "CDM", ovr: 69 },
                { nome: "M. Senaya", idade: 24, posicao: "RB", ovr: 69 },
                { nome: "O. El Azzouzi", idade: 24, posicao: "CDM", ovr: 68 },
                { nome: "L. Coulibaly", idade: 22, posicao: "RM", ovr: 68 },
                { nome: "F. Oppegård", idade: 22, posicao: "LB", ovr: 67 },
                { nome: "L. Sy", idade: 22, posicao: "RB", ovr: 66 },
                { nome: "T. De Percin", idade: 24, posicao: "GK", ovr: 66 },
                { nome: "N. Buayi-Kiala", idade: 21, posicao: "CM", ovr: 62 },
                { nome: "T. Siwe", idade: 20, posicao: "CB", ovr: 60 },
                { nome: "R. Matondo", idade: 17, posicao: "CM", ovr: 59 },
                { nome: "R. Mandengue", idade: 19, posicao: "LM", ovr: 59 },
                { nome: "R. Rodin", idade: 19, posicao: "ST", ovr: 59 },
                { nome: "E. Legros", idade: 17, posicao: "CB", ovr: 59 },
                { nome: "T. Negrel", idade: 22, posicao: "GK", ovr: 59 },
                { nome: "T. Devernois", idade: 17, posicao: "CM", ovr: 58 },
                { nome: "L. Mezerette", idade: 18, posicao: "GK", ovr: 58 }
            ]
        },
        "Ligue 2 (OVR 68)": {
            "Reims": [
                { nome: "K. Nakamura", idade: 24, posicao: "LM", ovr: 76 },
                { nome: "T. Teuma", idade: 31, posicao: "CAM", ovr: 75 },
                { nome: "Akieme", idade: 27, posicao: "LB", ovr: 73 },
                { nome: "M. Daramy", idade: 23, posicao: "ST", ovr: 73 },
                { nome: "J. Okumu", idade: 28, posicao: "RCB", ovr: 73 },
                { nome: "N. Pallois", idade: 37, posicao: "LCB", ovr: 73 },
                { nome: "T. Leoni", idade: 25, posicao: "CM", ovr: 72 },
                { nome: "A. Leautey", idade: 29, posicao: "RM", ovr: 71 },
                { nome: "H. Sekine", idade: 22, posicao: "RB", ovr: 71 },
                { nome: "M. Gbane", idade: 24, posicao: "LDM", ovr: 70 },
                { nome: "Y. Demoncy", idade: 29, posicao: "RDM", ovr: 69 },
                { nome: "Y. Fofana", idade: 21, posicao: "CM", ovr: 68 },
                { nome: "M. Busi", idade: 25, posicao: "RB", ovr: 68 },
                { nome: "A. Olliero", idade: 29, posicao: "GK", ovr: 68 },
                { nome: "E. Jaouen", idade: 19, posicao: "GK", ovr: 68 },
                { nome: "A. Salama", idade: 24, posicao: "ST", ovr: 67 },
                { nome: "John Patrick", idade: 21, posicao: "CM", ovr: 66 },
                { nome: "N. Bassette", idade: 20, posicao: "ST", ovr: 66 },
                { nome: "V. Burlet", idade: 19, posicao: "LB", ovr: 66 },
                { nome: "A. Bojang", idade: 21, posicao: "ST", ovr: 64 },
                { nome: "E. N'Tamon", idade: 21, posicao: "CB", ovr: 64 },
                { nome: "A. Koné", idade: 20, posicao: "RB", ovr: 63 },
                { nome: "H. Ibrahim", idade: 19, posicao: "ST", ovr: 62 },
                { nome: "P. Zabi", idade: 18, posicao: "CM", ovr: 61 },
                { nome: "T. Diarra", idade: 22, posicao: "LW", ovr: 61 },
                { nome: "A. Tia", idade: 18, posicao: "CAM", ovr: 60 },
                { nome: "S. Sylla", idade: 21, posicao: "GK", ovr: 60 },
                { nome: "I. Orazi", idade: 18, posicao: "LW", ovr: 55 }
            ],
            "Montpellier": [
                { nome: "T. Savanier", idade: 33, posicao: "CAM", ovr: 75 },
                { nome: "B. Omeragić", idade: 23, posicao: "CB", ovr: 74 },
                { nome: "J. Laporte", idade: 31, posicao: "RCB", ovr: 73 },
                { nome: "L. Mincarelli", idade: 21, posicao: "LB", ovr: 71 },
                { nome: "E. Tchato", idade: 22, posicao: "RB", ovr: 71 },
                { nome: "A. Mendy", idade: 31, posicao: "RS", ovr: 71 },
                { nome: "C. Jullien", idade: 32, posicao: "LCB", ovr: 71 },
                { nome: "K. Fayad", idade: 21, posicao: "LCM", ovr: 70 },
                { nome: "N. Mbuku", idade: 23, posicao: "LS", ovr: 70 },
                { nome: "T. Sainte-Luce", idade: 26, posicao: "LB", ovr: 69 },
                { nome: "Y. Mouanga", idade: 19, posicao: "CB", ovr: 66 },
                { nome: "M. Michel", idade: 33, posicao: "GK", ovr: 66 },
                { nome: "S. Ngapandouetnbu", idade: 22, posicao: "GK", ovr: 66 },
                { nome: "Everson Junior", idade: 21, posicao: "RCM", ovr: 64 },
                { nome: "N. Pays", idade: 21, posicao: "CAM", ovr: 64 },
                { nome: "A. Sishuba", idade: 20, posicao: "CAM", ovr: 64 },
                { nome: "W. Ndollo Bille", idade: 20, posicao: "RB", ovr: 64 },
                { nome: "Y. Issoufou", idade: 18, posicao: "CM", ovr: 62 },
                { nome: "J. Ndiaye", idade: 20, posicao: "ST", ovr: 62 },
                { nome: "T. Chennahi", idade: 20, posicao: "CM", ovr: 61 },
                { nome: "A. Gueguin", idade: 20, posicao: "LM", ovr: 61 },
                { nome: "N. El Hannach", idade: 18, posicao: "CB", ovr: 61 },
                { nome: "V. Orakpo", idade: 19, posicao: "ST", ovr: 60 },
                { nome: "F. El Mahboub", idade: 17, posicao: "RW", ovr: 58 },
                { nome: "Y. Djemba", idade: 20, posicao: "CDM", ovr: 56 },
                { nome: "V. Džodić", idade: 18, posicao: "GK", ovr: 55 }
            ],
            "Grenoble": [
                { nome: "T. Valls", idade: 29, posicao: "LCM", ovr: 72 },
                { nome: "J. Benet", idade: 30, posicao: "RCM", ovr: 71 },
                { nome: "M. Diop", idade: 25, posicao: "GK", ovr: 69 },
                { nome: "S. Delos", idade: 26, posicao: "RB", ovr: 68 },
                { nome: "C. Vidal", idade: 25, posicao: "CB", ovr: 68 },
                { nome: "M. Xantippe", idade: 23, posicao: "LB", ovr: 67 },
                { nome: "G. Paquiez", idade: 31, posicao: "RCB", ovr: 66 },
                { nome: "M. Djitté", idade: 25, posicao: "ST", ovr: 66 },
                { nome: "S. Mambo", idade: 26, posicao: "CB", ovr: 66 },
                { nome: "A. Tchaptchet", idade: 23, posicao: "LCB", ovr: 66 },
                { nome: "H. Mbock", idade: 25, posicao: "CDM", ovr: 65 },
                { nome: "A. Kerouedan", idade: 25, posicao: "RW", ovr: 65 },
                { nome: "Y. Diaby", idade: 24, posicao: "LS", ovr: 65 },
                { nome: "L. Mouyokolo", idade: 24, posicao: "CB", ovr: 65 },
                { nome: "B. Allain", idade: 33, posicao: "GK", ovr: 65 },
                { nome: "B. Mouazan", idade: 23, posicao: "CAM", ovr: 64 },
                { nome: "M. Bangré", idade: 24, posicao: "RM", ovr: 64 },
                { nome: "S. Lélé Diba", idade: 21, posicao: "CDM", ovr: 62 },
                { nome: "N. Elphege", idade: 24, posicao: "RS", ovr: 62 },
                { nome: "M. Pattier", idade: 29, posicao: "GK", ovr: 62 },
                { nome: "M. Bechikh", idade: 19, posicao: "ST", ovr: 61 },
                { nome: "E. Maurin", idade: 24, posicao: "ST", ovr: 61 },
                { nome: "B. Isola", idade: 24, posicao: "CDM", ovr: 60 },
                { nome: "E. Sarıkaya", idade: 19, posicao: "CB", ovr: 60 },
                { nome: "A. N'Gatta", idade: 21, posicao: "RB", ovr: 60 },
                { nome: "N. Zahui", idade: 22, posicao: "RM", ovr: 58 },
                { nome: "B. Yameogo", idade: 20, posicao: "CDM", ovr: 57 },
                { nome: "L. Jarjou", idade: 23, posicao: "RW", ovr: 57 },
                { nome: "M. Mion", idade: 24, posicao: "LB", ovr: 57 },
                { nome: "C. Dressel", idade: 19, posicao: "CM", ovr: 55 }
            ],
            "Guingamp": [
                { nome: "A. Sissoko", idade: 28, posicao: "RB", ovr: 71 },
                { nome: "K. Sidibé", idade: 26, posicao: "RCM", ovr: 71 },
                { nome: "A. Hemia", idade: 27, posicao: "LS", ovr: 70 },
                { nome: "L. Mafouta", idade: 30, posicao: "RS", ovr: 70 },
                { nome: "D. Gomis", idade: 30, posicao: "RCB", ovr: 70 },
                { nome: "Adrián Ortolá", idade: 31, posicao: "GK", ovr: 70 },
                { nome: "D. Louiserre", idade: 30, posicao: "LCM", ovr: 68 },
                { nome: "E. Koffi", idade: 30, posicao: "RB", ovr: 68 },
                { nome: "S. Nair", idade: 23, posicao: "CB", ovr: 68 },
                { nome: "A. Abdallah", idade: 27, posicao: "LB", ovr: 66 },
                { nome: "A. Sagna", idade: 26, posicao: "RM", ovr: 66 },
                { nome: "D. Ourega", idade: 20, posicao: "LB", ovr: 65 },
                { nome: "D. Nlandu", idade: 24, posicao: "CAM", ovr: 63 },
                { nome: "G. Ott", idade: 23, posicao: "LM", ovr: 63 },
                { nome: "T. Bartouche-Selbonne", idade: 28, posicao: "GK", ovr: 62 },
                { nome: "F. Mbemba", idade: 22, posicao: "ST", ovr: 61 },
                { nome: "J. Hatchi", idade: 20, posicao: "LM", ovr: 61 },
                { nome: "J. Matumona", idade: 19, posicao: "RB", ovr: 61 },
                { nome: "A. Démouchy", idade: 23, posicao: "LCB", ovr: 61 },
                { nome: "S. Kielt", idade: 23, posicao: "ST", ovr: 59 },
                { nome: "N. Marec", idade: 20, posicao: "GK", ovr: 59 },
                { nome: "T. Ahile", idade: 20, posicao: "CDM", ovr: 58 },
                { nome: "Y. Njoya", idade: 21, posicao: "LM", ovr: 58 },
                { nome: "E. Gassama", idade: 19, posicao: "CB", ovr: 57 },
                { nome: "I. Planeix", idade: 18, posicao: "CB", ovr: 56 }
            ],
            "Amiens": [
                { nome: "P. Bernardoni", idade: 28, posicao: "GK", ovr: 71 },
                { nome: "K. Kaïboué", idade: 26, posicao: "LCB", ovr: 70 },
                { nome: "N. Kandil", idade: 23, posicao: "LM", ovr: 69 },
                { nome: "J. Mlakar", idade: 26, posicao: "ST", ovr: 67 },
                { nome: "V. Lobry", idade: 30, posicao: "CAM", ovr: 66 },
                { nome: "T. Monconduit", idade: 34, posicao: "LDM", ovr: 66 },
                { nome: "R. Lutin", idade: 22, posicao: "LM", ovr: 66 },
                { nome: "A. Appiah", idade: 24, posicao: "LB", ovr: 66 },
                { nome: "A. Sauvage", idade: 33, posicao: "GK", ovr: 66 },
                { nome: "I. Hamache", idade: 22, posicao: "LM", ovr: 65 },
                { nome: "A. Lô", idade: 25, posicao: "CB", ovr: 65 },
                { nome: "J. Nduquidi", idade: 20, posicao: "CDM", ovr: 63 },
                { nome: "S. Bakayoko", idade: 20, posicao: "RCB", ovr: 62 },
                { nome: "I. Fofana", idade: 21, posicao: "RDM", ovr: 61 },
                { nome: "C. Louis", idade: 20, posicao: "LB", ovr: 61 },
                { nome: "Y. Ikia Dimi", idade: 20, posicao: "LM", ovr: 61 },
                { nome: "J. Chibozo", idade: 22, posicao: "CAM", ovr: 60 },
                { nome: "Y. Rafii", idade: 20, posicao: "ST", ovr: 60 },
                { nome: "T. Andami Averlant", idade: 25, posicao: "RM", ovr: 60 },
                { nome: "A. Chabane", idade: 18, posicao: "RB", ovr: 60 },
                { nome: "M. Touho", idade: 20, posicao: "LM", ovr: 59 },
                { nome: "M. Manitu", idade: 19, posicao: "LM", ovr: 59 },
                { nome: "M. Tine", idade: 23, posicao: "CAM", ovr: 58 },
                { nome: "N. Talbot", idade: 17, posicao: "RB", ovr: 54 },
                { nome: "L. Alexandre", idade: 19, posicao: "GK", ovr: 54 },
                { nome: "C. Injai", idade: 19, posicao: "CAM", ovr: 53 }
            ],
            "Clermont Foot": [
                { nome: "J. Gastien", idade: 37, posicao: "RDM", ovr: 69 },
                { nome: "Y. Salmier", idade: 32, posicao: "LCB", ovr: 69 },
                { nome: "A. Bamba", idade: 31, posicao: "LM", ovr: 68 },
                { nome: "M. Caufriez", idade: 28, posicao: "RCB", ovr: 68 },
                { nome: "H. Saivet", idade: 34, posicao: "LDM", ovr: 67 },
                { nome: "M. Douane", idade: 22, posicao: "LM", ovr: 67 },
                { nome: "F. Diédhiou", idade: 32, posicao: "ST", ovr: 66 },
                { nome: "T. Guivarch", idade: 29, posicao: "GK", ovr: 66 },
                { nome: "C. Konaté", idade: 21, posicao: "RB", ovr: 65 },
                { nome: "M. Ndiaye", idade: 23, posicao: "GK", ovr: 65 },
                { nome: "A. Hunou", idade: 31, posicao: "CAM", ovr: 64 },
                { nome: "K. Boto", idade: 29, posicao: "LB", ovr: 64 },
                { nome: "A. Camblan", idade: 21, posicao: "RM", ovr: 63 },
                { nome: "O. Diop", idade: 20, posicao: "RM", ovr: 63 },
                { nome: "A. Ackra", idade: 21, posicao: "CDM", ovr: 62 },
                { nome: "L. Socka", idade: 26, posicao: "ST", ovr: 61 },
                { nome: "I. Coulibaly", idade: 19, posicao: "RB", ovr: 60 },
                { nome: "Y. Bellache", idade: 22, posicao: "CAM", ovr: 60 },
                { nome: "J. Mwimba Isala", idade: 22, posicao: "CB", ovr: 60 },
                { nome: "E. Cantero", idade: 20, posicao: "RM", ovr: 59 },
                { nome: "J. Astic", idade: 20, posicao: "CDM", ovr: 59 },
                { nome: "A. Baallal", idade: 20, posicao: "LM", ovr: 58 },
                { nome: "S. Berkani", idade: 21, posicao: "CDM", ovr: 57 },
                { nome: "A. Saïd", idade: 22, posicao: "ST", ovr: 57 },
                { nome: "I. M'Bahia", idade: 20, posicao: "CB", ovr: 57 },
                { nome: "M. Donavin", idade: 18, posicao: "CB", ovr: 57 },
                { nome: "I. Fakili", idade: 19, posicao: "LM", ovr: 57 },
                { nome: "S. Awudu", idade: 20, posicao: "LB", ovr: 56 }
            ],
            "Pau FC": [
                { nome: "A. Briançon", idade: 30, posicao: "RCB", ovr: 69 },
                { nome: "A. Bobichon", idade: 29, posicao: "CAM", ovr: 68 },
                { nome: "J. Ruiz", idade: 27, posicao: "LCB", ovr: 67 },
                { nome: "T. Pouilly", idade: 22, posicao: "RB", ovr: 66 },
                { nome: "S. Beusnard", idade: 33, posicao: "LDM", ovr: 65 },
                { nome: "O. Kanté", idade: 35, posicao: "CB", ovr: 65 },
                { nome: "E. Salles", idade: 31, posicao: "GK", ovr: 65 },
                { nome: "D. Meddah", idade: 22, posicao: "RDM", ovr: 64 },
                { nome: "K. Dong", idade: 20, posicao: "RM", ovr: 64 },
                { nome: "K. Gasnier", idade: 23, posicao: "CAM", ovr: 63 },
                { nome: "O. Sadik", idade: 21, posicao: "ST", ovr: 63 },
                { nome: "J. Kalulu", idade: 20, posicao: "LB", ovr: 62 },
                { nome: "E. Zuliani", idade: 20, posicao: "CAM", ovr: 62 },
                { nome: "R. Messi", idade: 18, posicao: "LM", ovr: 62 },
                { nome: "R. Touzghar", idade: 21, posicao: "CM", ovr: 61 },
                { nome: "G. Versini", idade: 21, posicao: "RM", ovr: 61 },
                { nome: "T. Paradowski", idade: 20, posicao: "GK", ovr: 61 },
                { nome: "N. Glossoa", idade: 20, posicao: "CB", ovr: 60 },
                { nome: "O. Sissoko", idade: 18, posicao: "ST", ovr: 60 },
                { nome: "S. Karamoko", idade: 25, posicao: "CB", ovr: 59 },
                { nome: "N. Raveyre", idade: 20, posicao: "GK", ovr: 59 },
                { nome: "S. Lebouath", idade: 23, posicao: "RM", ovr: 58 },
                { nome: "E. Derouin", idade: 17, posicao: "LB", ovr: 58 },
                { nome: "C. Fall", idade: 21, posicao: "CM", ovr: 57 }
            ],
            "Bastia": [
                { nome: "T. Ducrocq", idade: 25, posicao: "RDM", ovr: 70 },
                { nome: "Z. Ariss", idade: 21, posicao: "LB", ovr: 69 },
                { nome: "A. Boutrah", idade: 24, posicao: "LM", ovr: 69 },
                { nome: "J. Placide", idade: 37, posicao: "GK", ovr: 69 },
                { nome: "J. Janneh", idade: 22, posicao: "LDM", ovr: 68 },
                { nome: "G. Akueson", idade: 29, posicao: "CB", ovr: 67 },
                { nome: "C. Vincent", idade: 32, posicao: "CAM", ovr: 66 },
                { nome: "F. Bohnert", idade: 27, posicao: "RB", ovr: 66 },
                { nome: "D. Guidi", idade: 29, posicao: "RCB", ovr: 66 },
                { nome: "J. Sebas", idade: 22, posicao: "ST", ovr: 66 },
                { nome: "T. Meynadier", idade: 25, posicao: "RB", ovr: 65 },
                { nome: "F. Tomi", idade: 24, posicao: "RM", ovr: 64 },
                { nome: "A. Roncaglia", idade: 25, posicao: "LCB", ovr: 64 },
                { nome: "J. Guevara", idade: 24, posicao: "CB", ovr: 63 },
                { nome: "I. Karamoko", idade: 23, posicao: "LM", ovr: 62 },
                { nome: "M. Blé", idade: 22, posicao: "ST", ovr: 62 },
                { nome: "A. Aiki", idade: 20, posicao: "RM", ovr: 62 },
                { nome: "L. Gueho", idade: 21, posicao: "CB", ovr: 62 },
                { nome: "N. Parravicini", idade: 27, posicao: "ST", ovr: 62 },
                { nome: "J. Fabri", idade: 31, posicao: "GK", ovr: 62 },
                { nome: "L. Etoga", idade: 22, posicao: "CDM", ovr: 61 },
                { nome: "L. Olmeta", idade: 19, posicao: "GK", ovr: 60 },
                { nome: "Y. Bathily", idade: 22, posicao: "CM", ovr: 57 },
                { nome: "N. Zilliox", idade: 22, posicao: "CB", ovr: 57 },
                { nome: "D. Basset", idade: 21, posicao: "CB", ovr: 57 },
                { nome: "S. Contena", idade: 19, posicao: "GK", ovr: 57 },
                { nome: "A. Zaouai", idade: 20, posicao: "CAM", ovr: 56 }
            ],
            "Troyes": [
                { nome: "N. Lemaître", idade: 28, posicao: "GK", ovr: 70 },
                { nome: "A. Mille", idade: 27, posicao: "RCM", ovr: 69 },
                { nome: "A. Monfray", idade: 34, posicao: "RCB", ovr: 69 },
                { nome: "I. Boura", idade: 24, posicao: "LB", ovr: 68 },
                { nome: "Y. Larouci", idade: 24, posicao: "LM", ovr: 68 },
                { nome: "H. Gambor", idade: 22, posicao: "RB", ovr: 68 },
                { nome: "X. Chavalerin", idade: 34, posicao: "LCM", ovr: 67 },
                { nome: "M. Ifnaoui", idade: 26, posicao: "CAM", ovr: 67 },
                { nome: "T. Bentayeb", idade: 23, posicao: "ST", ovr: 67 },
                { nome: "M. El Idrissy", idade: 26, posicao: "ST", ovr: 66 },
                { nome: "T. Baldé", idade: 23, posicao: "RB", ovr: 66 },
                { nome: "M. Adeline", idade: 21, posicao: "CM", ovr: 65 },
                { nome: "L. Maronnier", idade: 25, posicao: "LB", ovr: 65 },
                { nome: "Z. Boucher", idade: 33, posicao: "GK", ovr: 65 },
                { nome: "A. Bruus", idade: 26, posicao: "RB", ovr: 64 },
                { nome: "M. Diop", idade: 24, posicao: "CDM", ovr: 64 },
                { nome: "A. Phliponeau", idade: 25, posicao: "CDM", ovr: 64 },
                { nome: "P. Gozzi", idade: 24, posicao: "LCB", ovr: 64 },
                { nome: "J. Assoumou", idade: 22, posicao: "RM", ovr: 63 },
                { nome: "Y. Titi", idade: 19, posicao: "RB", ovr: 63 },
                { nome: "N. Cervantes", idade: 22, posicao: "RM", ovr: 62 },
                { nome: "H. Konaté", idade: 30, posicao: "GK", ovr: 62 },
                { nome: "I. Traoré", idade: 19, posicao: "LM", ovr: 59 },
                { nome: "M. Detourbet", idade: 18, posicao: "ST", ovr: 59 },
                { nome: "T. Akpakoun", idade: 20, posicao: "CB", ovr: 59 },
                { nome: "S. Diawara", idade: 19, posicao: "CB", ovr: 59 },
                { nome: "A. Ouzenadji", idade: 18, posicao: "LB", ovr: 58 },
                { nome: "A. Sidibé", idade: 20, posicao: "RM", ovr: 58 },
                { nome: "E. Odede", idade: 18, posicao: "LW", ovr: 58 },
                { nome: "M. Hamdi", idade: 21, posicao: "LB", ovr: 58 },
                { nome: "R. Murcy", idade: 19, posicao: "CM", ovr: 57 },
                { nome: "A. Diakité", idade: 20, posicao: "RW", ovr: 57 },
                { nome: "A. Nadé", idade: 18, posicao: "ST", ovr: 54 }
            ],
            "Nancy": [
                { nome: "E. Basilio", idade: 30, posicao: "GK", ovr: 71 },
                { nome: "F. Maouassa", idade: 26, posicao: "LB", ovr: 69 },
                { nome: "A. Dabasse", idade: 31, posicao: "ST", ovr: 66 },
                { nome: "W. Bouabdeli", idade: 24, posicao: "CAM", ovr: 65 },
                { nome: "N. Saint-Ruf", idade: 32, posicao: "RCB", ovr: 65 },
                { nome: "M. Sourzac", idade: 33, posicao: "GK", ovr: 64 },
                { nome: "R. Bamba", idade: 21, posicao: "RB", ovr: 63 },
                { nome: "T. Bouriaud", idade: 28, posicao: "LDM", ovr: 63 },
                { nome: "B. Bokangu", idade: 25, posicao: "ST", ovr: 62 },
                { nome: "M. Expérience", idade: 26, posicao: "LB", ovr: 62 },
                { nome: "J. Evans", idade: 26, posicao: "LM", ovr: 62 },
                { nome: "N. Fernandez", idade: 20, posicao: "LCB", ovr: 62 },
                { nome: "C. Touré", idade: 28, posicao: "ST", ovr: 62 },
                { nome: "O. Sidibé", idade: 24, posicao: "RM", ovr: 62 },
                { nome: "Y. Nahounou", idade: 21, posicao: "CB", ovr: 62 },
                { nome: "Ć. Suljić", idade: 28, posicao: "CM", ovr: 61 },
                { nome: "M. Carlier", idade: 28, posicao: "RDM", ovr: 61 },
                { nome: "A. Julloux", idade: 28, posicao: "RB", ovr: 61 },
                { nome: "Z. Fdaouch", idade: 28, posicao: "LM", ovr: 61 },
                { nome: "E. Mendy", idade: 25, posicao: "CB", ovr: 61 },
                { nome: "B. Camara", idade: 31, posicao: "CDM", ovr: 60 },
                { nome: "P. Ouotro", idade: 19, posicao: "ST", ovr: 60 },
                { nome: "C. El Hansar", idade: 20, posicao: "CDM", ovr: 58 },
                { nome: "Z. Ztouti", idade: 18, posicao: "ST", ovr: 56 }
            ],
            "Saint-Étienne": [
                { nome: "L. Stassin", idade: 20, posicao: "ST", ovr: 75 },
                { nome: "Z. Davitashvili", idade: 24, posicao: "LW", ovr: 74 },
                { nome: "G. Larsonneur", idade: 28, posicao: "GK", ovr: 74 },
                { nome: "I. Cardona", idade: 27, posicao: "RW", ovr: 73 },
                { nome: "P. Ekwah", idade: 23, posicao: "CDM", ovr: 71 },
                { nome: "F. Tardieu", idade: 33, posicao: "CDM", ovr: 71 },
                { nome: "João Ferreira", idade: 24, posicao: "RB", ovr: 71 },
                { nome: "D. Appiah", idade: 33, posicao: "RB", ovr: 71 },
                { nome: "D. Batubinsika", idade: 29, posicao: "CB", ovr: 71 },
                { nome: "M. Nadé", idade: 26, posicao: "LCB", ovr: 71 },
                { nome: "Y. Maçon", idade: 26, posicao: "LB", ovr: 70 },
                { nome: "Chico Lamba", idade: 22, posicao: "RCB", ovr: 70 },
                { nome: "B. Maubleu", idade: 35, posicao: "GK", ovr: 70 },
                { nome: "M. Bernauer", idade: 27, posicao: "CB", ovr: 69 },
                { nome: "A. Boakye", idade: 24, posicao: "RW", ovr: 69 },
                { nome: "A. Moueffek", idade: 24, posicao: "LCM", ovr: 68 },
                { nome: "B. Old", idade: 22, posicao: "LW", ovr: 68 },
                { nome: "E. Annan", idade: 22, posicao: "LB", ovr: 67 },
                { nome: "M. Jaber", idade: 25, posicao: "RCM", ovr: 64 },
                { nome: "I. Miladinović", idade: 22, posicao: "CAM", ovr: 63 },
                { nome: "J. Duffus", idade: 20, posicao: "ST", ovr: 61 },
                { nome: "D. N'Guessan", idade: 16, posicao: "ST", ovr: 61 },
                { nome: "L. Traoré", idade: 18, posicao: "LB", ovr: 59 },
                { nome: "N. El Jamali", idade: 18, posicao: "CM", ovr: 58 },
                { nome: "L. Gadegbeku", idade: 18, posicao: "CM", ovr: 58 },
                { nome: "S. Stojković", idade: 18, posicao: "RB", ovr: 57 }
            ],
            "Laval": [
                { nome: "M. Samassa", idade: 35, posicao: "GK", ovr: 72 },
                { nome: "T. Vargas", idade: 25, posicao: "RB", ovr: 71 },
                { nome: "S. Sanna", idade: 26, posicao: "LCM", ovr: 69 },
                { nome: "T. Pellenard", idade: 31, posicao: "LCB", ovr: 69 },
                { nome: "M. Tchokounté", idade: 36, posicao: "ST", ovr: 69 },
                { nome: "M. Sellouki", idade: 25, posicao: "RM", ovr: 68 },
                { nome: "Yohan Tavares", idade: 37, posicao: "CB", ovr: 68 },
                { nome: "J. Maggiotti", idade: 29, posicao: "RCM", ovr: 67 },
                { nome: "C. Mandouki", idade: 33, posicao: "CDM", ovr: 67 },
                { nome: "M. Camara", idade: 24, posicao: "LM", ovr: 66 },
                { nome: "P. Ouaneh", idade: 27, posicao: "CB", ovr: 66 },
                { nome: "T. Thomas", idade: 23, posicao: "CM", ovr: 65 },
                { nome: "W. Bianda", idade: 25, posicao: "CB", ovr: 64 },
                { nome: "E. Maddy", idade: 24, posicao: "RM", ovr: 63 },
                { nome: "M. Adilèhou", idade: 29, posicao: "RCB", ovr: 63 },
                { nome: "M. Hautbois", idade: 34, posicao: "GK", ovr: 63 },
                { nome: "Y. Aradj", idade: 20, posicao: "LB", ovr: 62 },
                { nome: "E. Montet", idade: 22, posicao: "CDM", ovr: 61 },
                { nome: "A. Faurand-Tournaire", idade: 21, posicao: "ST", ovr: 60 },
                { nome: "W. Benard", idade: 22, posicao: "CM", ovr: 59 },
                { nome: "N. Mupemba", idade: 22, posicao: "ST", ovr: 58 },
                { nome: "M. Commaret", idade: 23, posicao: "CB", ovr: 57 },
                { nome: "E. Clavreul", idade: 19, posicao: "CAM", ovr: 56 },
                { nome: "M. Ntessa", idade: 16, posicao: "GK", ovr: 54 }
            ],
            "Dunkerque": [
                { nome: "E. Bardeli", idade: 24, posicao: "LCM", ovr: 71 },
                { nome: "V. Sasso", idade: 34, posicao: "LCB", ovr: 71 },
                { nome: "Eguaras", idade: 33, posicao: "CDM", ovr: 70 },
                { nome: "A. Georgen", idade: 26, posicao: "RB", ovr: 70 },
                { nome: "O. Sangante", idade: 34, posicao: "RCB", ovr: 70 },
                { nome: "Felipe Abner", idade: 29, posicao: "LB", ovr: 69 },
                { nome: "T. Robinet", idade: 28, posicao: "CAM", ovr: 66 },
                { nome: "E. Sylvestre", idade: 25, posicao: "CM", ovr: 65 },
                { nome: "A. Kanté", idade: 30, posicao: "ST", ovr: 65 },
                { nome: "G. Yassine", idade: 19, posicao: "LM", ovr: 65 },
                { nome: "P. Diong", idade: 19, posicao: "CDM", ovr: 65 },
                { nome: "A. Linguet", idade: 25, posicao: "RM", ovr: 64 },
                { nome: "A. Sekongo", idade: 21, posicao: "CM", ovr: 63 },
                { nome: "M. Diop", idade: 19, posicao: "RCM", ovr: 63 },
                { nome: "M. Niflore", idade: 18, posicao: "GK", ovr: 63 },
                { nome: "Marcos Lavín", idade: 28, posicao: "GK", ovr: 63 },
                { nome: "G. Kondo", idade: 23, posicao: "LB", ovr: 62 },
                { nome: "M. Essimi", idade: 26, posicao: "LM", ovr: 62 },
                { nome: "A. Zossou", idade: 20, posicao: "LM", ovr: 61 },
                { nome: "T. Massock", idade: 17, posicao: "CDM", ovr: 61 },
                { nome: "A. Daho", idade: 21, posicao: "LM", ovr: 60 },
                { nome: "V. Mayela", idade: 21, posicao: "CB", ovr: 60 },
                { nome: "L. Dziki", idade: 20, posicao: "RB", ovr: 56 },
                { nome: "A. N'Doye", idade: 21, posicao: "LB", ovr: 55 }
            ],
            "Red Star": [
                { nome: "G. Poussin", idade: 26, posicao: "GK", ovr: 72 },
                { nome: "S. Khaoui", idade: 30, posicao: "CAM", ovr: 70 },
                { nome: "G. Haag", idade: 25, posicao: "CDM", ovr: 70 },
                { nome: "P. Lemonnier", idade: 31, posicao: "CB", ovr: 68 },
                { nome: "R. Hachem", idade: 27, posicao: "RCM", ovr: 67 },
                { nome: "D. Durand", idade: 29, posicao: "LS", ovr: 67 },
                { nome: "B. Danger", idade: 27, posicao: "CB", ovr: 66 },
                { nome: "M. Huard", idade: 27, posicao: "LCB", ovr: 66 },
                { nome: "H. Benali", idade: 25, posicao: "ST", ovr: 66 },
                { nome: "Q. Beunardeau", idade: 31, posicao: "GK", ovr: 66 },
                { nome: "S. Renel", idade: 23, posicao: "CM", ovr: 65 },
                { nome: "D. Durivaux", idade: 24, posicao: "RCB", ovr: 65 },
                { nome: "K. Cabral", idade: 25, posicao: "RM", ovr: 65 },
                { nome: "J. Eickmayer", idade: 32, posicao: "LCM", ovr: 64 },
                { nome: "D. Sylla", idade: 22, posicao: "RM", ovr: 64 },
                { nome: "G. Trani", idade: 27, posicao: "CAM", ovr: 63 },
                { nome: "K. Cissé", idade: 28, posicao: "LM", ovr: 63 },
                { nome: "J. Kayi Sanda", idade: 18, posicao: "CB", ovr: 63 },
                { nome: "J. Escartin", idade: 22, posicao: "CB", ovr: 63 },
                { nome: "J. Ikanga", idade: 23, posicao: "RS", ovr: 60 },
                { nome: "A. Hachem", idade: 23, posicao: "ST", ovr: 60 },
                { nome: "V. Rabouille", idade: 25, posicao: "GK", ovr: 59 },
                { nome: "V. Kany", idade: 23, posicao: "CM", ovr: 58 },
                { nome: "I. Halifa", idade: 20, posicao: "CDM", ovr: 58 },
                { nome: "M. Ahamada", idade: 21, posicao: "RB", ovr: 58 },
                { nome: "R. Doucouré", idade: 24, posicao: "CB", ovr: 58 },
                { nome: "R. Slimani", idade: 21, posicao: "CM", ovr: 57 }
            ],
            "Annecy": [
                { nome: "F. Escales", idade: 29, posicao: "GK", ovr: 70 },
                { nome: "A. Kashi", idade: 36, posicao: "RDM", ovr: 69 },
                { nome: "A. Larose", idade: 32, posicao: "RM", ovr: 69 },
                { nome: "V. Pajot", idade: 34, posicao: "LDM", ovr: 68 },
                { nome: "F. N'Sakala", idade: 34, posicao: "LB", ovr: 67 },
                { nome: "A. Drouhin", idade: 25, posicao: "CB", ovr: 67 },
                { nome: "C. Billemaz", idade: 26, posicao: "LM", ovr: 66 },
                { nome: "F. Lajugie", idade: 29, posicao: "LCB", ovr: 65 },
                { nome: "J. Tiendrebeogo", idade: 22, posicao: "CAM", ovr: 64 },
                { nome: "T. Delphis", idade: 22, posicao: "RB", ovr: 64 },
                { nome: "J. Kouadio", idade: 25, posicao: "RCB", ovr: 64 },
                { nome: "B. Touré", idade: 21, posicao: "ST", ovr: 63 },
                { nome: "T. Callens", idade: 26, posicao: "GK", ovr: 63 },
                { nome: "A. Hbouch", idade: 26, posicao: "CAM", ovr: 61 },
                { nome: "Q. Paris", idade: 18, posicao: "LW", ovr: 61 },
                { nome: "M. Benama", idade: 20, posicao: "RB", ovr: 60 },
                { nome: "H. Koutoune", idade: 18, posicao: "RB", ovr: 60 },
                { nome: "T. Rambaud", idade: 28, posicao: "ST", ovr: 60 },
                { nome: "R. Neelakandan", idade: 20, posicao: "ST", ovr: 60 },
                { nome: "T. Rowe", idade: 18, posicao: "RB", ovr: 60 },
                { nome: "K. Jusseron Veniere", idade: 18, posicao: "LM", ovr: 59 },
                { nome: "C. Makutungu", idade: 27, posicao: "LB", ovr: 59 },
                { nome: "M. Veillon", idade: 23, posicao: "CB", ovr: 59 },
                { nome: "W. Debbiche", idade: 20, posicao: "CDM", ovr: 57 },
                { nome: "P. Venot", idade: 23, posicao: "CM", ovr: 56 },
                { nome: "M. Gonzalez", idade: 19, posicao: "GK", ovr: 54 },
                { nome: "A. Casadei", idade: 20, posicao: "CM", ovr: 53 },
                { nome: "I. Raache", idade: 19, posicao: "CM", ovr: 53 },
                { nome: "A. Nedelec", idade: 18, posicao: "GK", ovr: 50 }
            ],
            "Rodez": [
                { nome: "M. Tourraine", idade: 24, posicao: "RB", ovr: 69 },
                { nome: "A. Trouillet", idade: 24, posicao: "LCM", ovr: 68 },
                { nome: "Q. Braat", idade: 27, posicao: "GK", ovr: 68 },
                { nome: "W. Younoussa", idade: 23, posicao: "RCM", ovr: 67 },
                { nome: "T. Arconte", idade: 21, posicao: "LS", ovr: 65 },
                { nome: "N. Galves", idade: 21, posicao: "RB", ovr: 65 },
                { nome: "I. Baldé", idade: 22, posicao: "RS", ovr: 65 },
                { nome: "L. Laurent", idade: 24, posicao: "CB", ovr: 65 },
                { nome: "S. Benchamma", idade: 25, posicao: "CDM", ovr: 63 },
                { nome: "K. Nagera", idade: 23, posicao: "ST", ovr: 63 },
                { nome: "M. Magnin", idade: 23, posicao: "CB", ovr: 63 },
                { nome: "J. Evan's", idade: 26, posicao: "LB", ovr: 62 },
                { nome: "R. Lipinski", idade: 22, posicao: "LCB", ovr: 62 },
                { nome: "O. Joly", idade: 22, posicao: "CDM", ovr: 62 },
                { nome: "M. Baaloudj", idade: 24, posicao: "ST", ovr: 62 },
                { nome: "C. Jolibois", idade: 27, posicao: "CB", ovr: 62 },
                { nome: "A. Pelon", idade: 21, posicao: "RCB", ovr: 62 },
                { nome: "M. Achi", idade: 23, posicao: "CM", ovr: 61 },
                { nome: "D. Vangi", idade: 19, posicao: "CB", ovr: 61 },
                { nome: "L. Margueron", idade: 24, posicao: "GK", ovr: 61 },
                { nome: "E. Crombez", idade: 22, posicao: "GK", ovr: 61 },
                { nome: "J. Mendes", idade: 21, posicao: "CDM", ovr: 60 },
                { nome: "M. Saka", idade: 18, posicao: "CM", ovr: 60 },
                { nome: "H. Tebily", idade: 23, posicao: "ST", ovr: 59 },
                { nome: "C. Issanchou", idade: 20, posicao: "LB", ovr: 58 },
                { nome: "R. Ponti", idade: 27, posicao: "LM", ovr: 58 },
                { nome: "M. Corredor", idade: 20, posicao: "ST", ovr: 55 },
                { nome: "Y. Dahalani", idade: 20, posicao: "CM", ovr: 53 }
            ],
            "Le Mans": [
                { nome: "B. Guillaume", idade: 30, posicao: "ST", ovr: 67 },
                { nome: "H. Voyer", idade: 28, posicao: "LCB", ovr: 67 },
                { nome: "E. Quarshie", idade: 29, posicao: "LCM", ovr: 66 },
                { nome: "D. Gueye", idade: 29, posicao: "LS", ovr: 66 },
                { nome: "T. Luvambo", idade: 25, posicao: "RM", ovr: 65 },
                { nome: "M. Robin", idade: 25, posicao: "RM", ovr: 65 },
                { nome: "L. Buades", idade: 27, posicao: "RB", ovr: 65 },
                { nome: "A. Rabillard", idade: 29, posicao: "RS", ovr: 65 },
                { nome: "S. Yohou", idade: 33, posicao: "CB", ovr: 65 },
                { nome: "N. Kocik", idade: 26, posicao: "GK", ovr: 65 },
                { nome: "T. Eyoum", idade: 23, posicao: "RCB", ovr: 64 },
                { nome: "A. Ribelin", idade: 29, posicao: "RB", ovr: 63 },
                { nome: "J. Vercruysse", idade: 24, posicao: "RCM", ovr: 63 },
                { nome: "L. Calodat", idade: 23, posicao: "LB", ovr: 63 },
                { nome: "A. Lauray", idade: 28, posicao: "CDM", ovr: 63 },
                { nome: "M. Gomes", idade: 20, posicao: "CDM", ovr: 63 },
                { nome: "I. Cossier", idade: 18, posicao: "CB", ovr: 63 },
                { nome: "M. Rossignol", idade: 21, posicao: "CM", ovr: 62 },
                { nome: "L. Abanda", idade: 25, posicao: "LB", ovr: 62 },
                { nome: "E. Colas", idade: 28, posicao: "LW", ovr: 62 },
                { nome: "A. Cissé", idade: 19, posicao: "CB", ovr: 62 },
                { nome: "B. Oggad", idade: 28, posicao: "LW", ovr: 60 },
                { nome: "E. Hatfout", idade: 25, posicao: "GK", ovr: 60 },
                { nome: "N. Boissé", idade: 19, posicao: "RB", ovr: 58 },
                { nome: "W. Harhouz", idade: 25, posicao: "ST", ovr: 57 },
                { nome: "A. Delbecque", idade: 23, posicao: "GK", ovr: 57 }
            ],
            "Boulogne": [
                { nome: "J. Boyer", idade: 27, posicao: "LB", ovr: 64 },
                { nome: "A. El Farissi", idade: 26, posicao: "LS", ovr: 63 },
                { nome: "J. Bultel", idade: 25, posicao: "LCM", ovr: 63 },
                { nome: "D. Thiam", idade: 35, posicao: "RCB", ovr: 63 },
                { nome: "N. Zohoré", idade: 24, posicao: "LCB", ovr: 63 },
                { nome: "I. Koné", idade: 35, posicao: "GK", ovr: 63 },
                { nome: "N. Fatar", idade: 23, posicao: "RW", ovr: 61 },
                { nome: "A. Platret", idade: 22, posicao: "RB", ovr: 61 },
                { nome: "N. Binet", idade: 21, posicao: "RCM", ovr: 61 },
                { nome: "C. Fatou", idade: 26, posicao: "ST", ovr: 61 },
                { nome: "G. Capuano", idade: 19, posicao: "ST", ovr: 61 },
                { nome: "S. Gourville", idade: 25, posicao: "CB", ovr: 61 },
                { nome: "L. Raillot", idade: 21, posicao: "CDM", ovr: 60 },
                { nome: "L. Siliadin", idade: 23, posicao: "LB", ovr: 60 },
                { nome: "A. Pinot", idade: 24, posicao: "CB", ovr: 60 },
                { nome: "S. Duflos", idade: 30, posicao: "RB", ovr: 59 },
                { nome: "C. Kitenge", idade: 23, posicao: "RM", ovr: 59 },
                { nome: "E. Mpembele Boula", idade: 23, posicao: "LM", ovr: 59 },
                { nome: "H. Touré", idade: 25, posicao: "CDM", ovr: 59 },
                { nome: "X. Lenogue", idade: 28, posicao: "GK", ovr: 59 },
                { nome: "S. Paillard", idade: 21, posicao: "RM", ovr: 58 },
                { nome: "S. Keita", idade: 19, posicao: "LM", ovr: 58 },
                { nome: "J. Kapenga", idade: 21, posicao: "CB", ovr: 58 },
                { nome: "Z. Koné", idade: 20, posicao: "RS", ovr: 58 },
                { nome: "A. Uriev", idade: 21, posicao: "GK", ovr: 58 },
                { nome: "L. Boiteau", idade: 19, posicao: "CAM", ovr: 57 },
                { nome: "F. Boulet", idade: 22, posicao: "ST", ovr: 56 }
            ]
        },
    }
};

// Devolve o elenco real de um clube pra edição/temporada certa, ou null se ainda não
// tivermos dados dele (ligas/edições não populadas ainda).
function elencoRealDoClube(nomeClube, temporada) {
    let edicao = (typeof edicaoFcDaTemporada === "function") ? edicaoFcDaTemporada(temporada) : "fc26";
    let porEdicao = jogadoresPorClubePorEdicao[edicao] || jogadoresPorClubePorEdicao.fc26;
    if (!porEdicao) return null;
    for (let liga in porEdicao) {
        if (porEdicao[liga][nomeClube]) return porEdicao[liga][nomeClube];
    }
    return null;
}
